### ISSUE TITLE
Add Bootstrap to the project

### ISSUE THREAD

**Issue by castwayalldc** [castwayalldc/spending-control#3]
Add Bootstrap to the project. 

Here'e an useful guide: 
https://www.amadousall.com/the-good-parts-of-bootstrap-4-you-are-missing-in-your-angular-material-projects/

**Comment by carlitosry** [comment]
**TO-DO**

- [ ] Install `npm install bootstrap --save`.
- [ ] Change name of  `src/styles.css` by   `src/styles.scss`.
- [ ] Update File `angular.json` with the config scss.
- [ ] Create new Directory `assets/styles/` to save the sass partials to create generic styles.

**En src/styles.scss**
- [ ] import the features requeired to integrate bootstrap. For example:  (`@import "~bootstrap/scss/functions"`).
